spring:
  application:
    name: book-client-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: book-core-service
              uri: http://localhost:8080 # Downstream service URL
              predicates:
                - Path=/books/**
              filters:
                - TokenRelay # Forwards the verified token downstream
  security:
    oauth2:
      resourceserver:
        jwt:
          # Used by the Gateway to pull public keys and verify signatures locally
          jwk-set-uri: http://localhost:9000/oauth2/jwks 
      client:
        registration:
          book-client-gateway:
            client-id: "book-client-gateway"
            client-secret: "secret"
            client-authentication-method: "client_secret_basic"
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/book-client-gateway"
            scope: openid, profile
        provider:
          book-client-gateway:
            authorization-uri: http://localhost:9000/oauth2/authorize
            token-uri: http://localhost:9000/oauth2/token
            issuer-uri: http://localhost:9000

server:
  port: 8081

logging:
  level:
    org.springframework.security: DEBUG