spring:
  application:
    name: book-core-service
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  datasource:
    url: null
    database: null
    username: null
    password: null
    driver-class-name: org.postgresql.Driver
  cloud:
    gcp:
      project-id: null
      credentials:
        location: null
  servlet:                                                                                                                                          
    multipart:                                                                                                                                      
      max-file-size: 50MB                                                                                              
      max-request-size: 50MB
  security:
    oauth2:
      resourceserver:
        jwt:
          # Used by the Gateway to pull public keys and verify signatures locally
          jwk-set-uri: http://localhost:9000/oauth2/jwks
gcs:
  bucket-name: null
  
server:
  servlet:
    context-path: /api