---
servers:
- url: "http://localhost:8080/book-tracking/api"
openapi: "3.0.3"
paths:
  /books/{bookId}/download:
    $ref: "./book-core-api.yaml#/paths/~1books~1{bookId}~1download"
  /users/me:
    $ref: "./book-core-api.yaml#/paths/~1users~1me"
  /books:
    $ref: "./book-core-api.yaml#/paths/~1books"
info:
  title: "merged spec"
  description: "merged spec"
  version: "1.0.0"
